stages:
    - update

init:
    stage: update
    script:
        - echo 'Actualizando proyecto a la ultima version...'
        - cd /var/www/teamspeak-api
        - git pull http://$GIT_USER:$GIT_PASS@gitlab.owc.cl/teamspeak/teamspeak-api.git